### PR TITLE
add close button to modal

### LINKED ISSUE #67: close button for info popup
Right now, once you've clicked on a facet there's no way to close the popup.  Especially on mobile, this makes the app hard to use.

### PR DESCRIPTION
**Pull request by paulswartz**
Closes #67

### CODE REVIEW

**Comment by ohnorobo** [comment]
Closing when you click anywhere on the infobox seems unexpected and breaks double-click-to-select.
I think adding a small [x] button someplace in the box would work better.

**Comment by paulswartz** [comment]
Just having the small x close the widget was what I meant to do; I'll take a look later.

**Comment by paulswartz** [comment]
And by later I mean before I go to work. Fixed.

**Comment by ohnorobo** [comment]
I'm still not seeing this. (I'm seeing the close button on the 'about' popup, which also closes the infobox, but no separate close button on the infoboxes.) Should I be looking somewhere other than http://paulswartz.github.io/finda/ ?

**Comment by paulswartz** [comment]
It only shows up if the browser is small enough to collapse the menu bar.
 I can make it always visible if you want.

On Fri, Mar 7, 2014 at 1:28 PM, Sarah Laplante notifications@github.comwrote:

> I'm still not seeing this. (I'm seeing the close button on the 'about'
> popup, which also closes the infobox, but no separate close button on the
> infoboxes.) Should I be looking somewhere other than
> http://paulswartz.github.io/finda/ ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/codeforboston/finda/pull/75#issuecomment-37052736
> .

## 

Paul Swartz
paulswartz at gmail dot com
http://paulswartz.net/

**Comment by ohnorobo** [comment]
It can't hurt to have it always visible. More weird to me is that the 'about' [x] also closes the infoboxes when clicked.

**Comment by paulswartz** [comment]
I'll take a look at both of those when I get home.

**Pull request merged**
