### PR TITLE
Update map.js

### PR DESCRIPTION
**Pull request by mjrouser**
New attribution parameters and OSM tiles

### CODE REVIEW

**Comment by paulswartz** [comment]
Hey Matthew! Thanks for taking another look at this.  It's still got a syntax error though: you can see it on your forked gh-pages at http://mjrouser.github.io/filter-template/.

**Comment by mjrouser** [comment]
Hi Paul.  I updated the code.  Should be alright now.  Do I need to make another pull request, or is it enough to simply commit again?

**Comment by paulswartz** [comment]
Another commit is fine; it'll show up here.

**Comment by mjrouser** [comment]
OK, done and done.

---

http://mjrouser.com

**Comment by paulswartz** [comment]
@mjrouser there's still an issue; looks like a missing quote.

@ohnorobo @beech The original issue (#8) mentions keeping the gh-pages branch using the MAPC  tiles.  Is that still the desired outcome here?

**Comment by ohnorobo** [comment]
@beechnut originally showed us the MAPC tileset, which have a nice neutral colorscheme, but only cover Mass., and so look unusual when zoomed way out. So #8  was opened to look into finding something more comprehensive.

The desired outcome for the gh-pages branch is tileset-agnostic, just something nice looking, comprehensive, and openly available.

**Comment by mjrouser** [comment]
That should do it.  Seems to have passed the check now

**Pull request merged**
