### PR TITLE
add popup on mouseover, add new attribute to config to...

### PR DESCRIPTION
**Pull request by isaacchansky**
...specify the feature property to use as the text for popup.

### CODE REVIEW

**Comment by ohnorobo** [comment]
I'm still seeing the flicker effect you mentioned earlier. Seems to have to do with different mouse targets between the regular pointy mouse cursor and the micky-mouse hand cursor. 
Does anyone know if the icon change is part of leafet?

**Comment by isaacchansky** [comment]
The Icon change does seem to be part of Leaflet. Leaflet's popups have an extra ~10px of invisible area below them which was highjacking the hover event, so just moving the popup up a little fixes it.

**Comment by paulswartz** [comment]
Couple things:
- I like how you broke the functionality into separate events; nice!
- Can you add some tests for the new functionality?
- What's going to happen if there's actually a field in the data called `preview_attribute`? Maybe it should be defined in the `map` sections?
- Is there a way to get the hiding to work? It's a little weird that the popup appears, but doesn't disappear.

**Comment by ohnorobo** [comment]
Also, if you select an icon the pop up aligns itself with the point of the icon instead of 10px above.

**Comment by isaacchansky** [comment]
@paulswartz thanks - I moved the `preview_attribute` into the `map` section. In hindsight having it in the `properties` is super confusing. Kind of feel like there should be a subsection in `map` to separate core map configuration and ui sugar (ex. if you wanted to add something like custom icons). Will get writing tests later today.

@ohnorobo ah good catch. That seems to also be occasionally happening to a few _other_ icons when one is selected too... will look into it.

**Comment by ohnorobo** [comment]
@isaacchansky, the problems with other icons you're seeing are probably related to #80 

Once this gets pulled in we should open another story so that clicking on the popup also opens the infobox.

**Comment by ohnorobo** [comment]
I just meant that #80 was probably the reason you were seeing it on features that weren't currently selected.

**Pull request merged**
